from __future__ import annotations

from datetime import datetime, timezone

from .models import Question


def load_sample_questions() -> list[Question]:
    now = datetime.now(timezone.utc)
    return [
        Question(
            question_id=101,
            title="How do I compare naive and aware datetimes in Python?",
            body="I keep getting TypeError when comparing datetime objects.",
            tags=["python", "datetime"],
            score=3,
            answer_count=0,
            view_count=1842,
            is_answered=False,
            link="https://stackoverflow.com/questions/101",
            owner="user-a",
            source="sample",
            creation_date=now,
            last_activity_date=now,
        ),
        Question(
            question_id=102,
            title="Why does SQLAlchemy lazy loading trigger extra queries?",
            body="I want to avoid N+1 issues in a small service.",
            tags=["python", "sqlalchemy", "orm"],
            score=4,
            answer_count=1,
            view_count=950,
            is_answered=True,
            accepted_answer_id=9001,
            link="https://stackoverflow.com/questions/102",
            owner="user-b",
            source="sample",
            creation_date=now,
            last_activity_date=now,
        ),
        Question(
            question_id=103,
            title="How do I return a borrowed string from a Rust function?",
            body="The compiler says borrowed value does not live long enough.",
            tags=["rust", "borrow-checker"],
            score=2,
            answer_count=0,
            view_count=1301,
            is_answered=False,
            link="https://stackoverflow.com/questions/103",
            owner="user-c",
            source="sample",
            creation_date=now,
            last_activity_date=now,
        ),
        Question(
            question_id=104,
            title="How do I stop useEffect firing twice in React 18?",
            body="The effect runs twice in dev and I need a stable pattern.",
            tags=["reactjs", "javascript", "hooks"],
            score=8,
            answer_count=2,
            view_count=2510,
            is_answered=False,
            link="https://stackoverflow.com/questions/104",
            owner="user-d",
            source="sample",
            creation_date=now,
            last_activity_date=now,
        ),
        Question(
            question_id=105,
            title="When should I use a partial index in PostgreSQL?",
            body="I have a sparse status column and a few hot queries.",
            tags=["postgresql", "database", "indexing"],
            score=5,
            answer_count=1,
            view_count=1122,
            is_answered=True,
            accepted_answer_id=9002,
            link="https://stackoverflow.com/questions/105",
            owner="user-e",
            source="sample",
            creation_date=now,
            last_activity_date=now,
        ),
        Question(
            question_id=106,
            title="How can I infer a generic type from object keys in TypeScript?",
            body="I need the compiler to carry the keys into the return type.",
            tags=["typescript", "generics", "types"],
            score=1,
            answer_count=0,
            view_count=732,
            is_answered=False,
            link="https://stackoverflow.com/questions/106",
            owner="user-f",
            source="sample",
            creation_date=now,
            last_activity_date=now,
        ),
    ]
